# Generated by Django 5.1.6 on 2025-03-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activation_link',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
