# Generated by Django 5.1.6 on 2025-03-26 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_activation_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'verbose_name': 'Generated Token',
                'verbose_name_plural': 'Generated Tokens',
            },
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
