# Generated by Django 5.1.6 on 2025-03-26 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_generatedtoken_delete_usertoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
