# Generated by Django 5.1.6 on 2025-03-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_generatedtoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_password_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
