# Generated by Django 5.1.6 on 2025-03-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_last_password_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_delete_request',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
