# Start from the official Python slim image
FROM python:3.11-slim

# Set environment variables for Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set the working directory
WORKDIR /app

# Install pip dependencies in a virtual environment
COPY requirements.txt /app/
RUN python -m venv venv && \
    venv/bin/pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application files
COPY . /app/

# Create the /app/media directory
RUN mkdir -p /app/media

CMD ["venv/bin/uvicorn", "website.asgi:application", "--host", "0.0.0.0", "--port", "8000"]